### ISSUE TITLE
Are these extensions suitable for use with VB.Net?

### ISSUE THREAD

**Issue by beppe9000** [vkhorikov/CSharpFunctionalExtensions#11]

**Comment by vkhorikov** [comment]
Yes, they should work perfectly fine in VB.NET too.

**Comment by beppe9000** [comment]
Thanks! I also had another question. Is there a way to implicitly cast a Result to Result<T> ?

**Comment by vkhorikov** [comment]
1) The conversion works only from `Result<T>` to `Result`, not the other way around. That's because you'd need some value in order to transform a success `Result` to a success `Result<T>`. As for failure conversion, you'd need to do `Result.Fail<T>("object is null")`

2) Only a success result can hold a value as of the current implementation.

**Comment by beppe9000** [comment]
Thanks for the information!
