### ISSUE TITLE
Maybe with Structs

### ISSUE THREAD

**Issue by gregberns** [vkhorikov/CSharpFunctionalExtensions#13]
Is there any way to support structs with Maybe? 

I removed the 'where T : class' from the code but then I found this issue:

```
struct Account{
public Guid Id;
}

Maybe<Account> SomeFunction(){
var list = new List<Account>();
return list.FirstOrDefault()
}

var result = SomeFunction();
//This is true!! it should be false
Assert.IsTrue(result.HasValue)
```

I want to make Account a struct  because I need to use use Entity Framework and its use of references (not immutability) is making my life crappy. So I tried to use structs for value passing, but now I can't seem to use Maybe. 

Any suggestions you have would be great. Hope I provided enough info.

**Comment by vkhorikov** [comment]
Hi @gregberns . Structs in .NET are inherently non-nullable, you can't assign null to an Account variable. This is why I originally added the restriction and this is why you are getting true instead of false.

Can you elaborate on your situation? It seems to me that just making `Account` a struct should be enough for you to make it non-nullable, no need to use Maybe here.

**Comment by vkhorikov** [comment]
Ah, I see. You can use `Nullable<>` for that. For example, declare a repository method like this:
`public Account? GetById(int id)`
and this will show the clients of your code that the method can return an empty value. Note that `Account?` is a short-cut and equivalent to `Nullable<Account>`. `Nullable<>` itself is a built-in type which plays the same role as `Maybe` but for structs, not reference types.

**Comment by gregberns** [comment]
Ah, that may work, Thanks!!
