### ISSUE TITLE
[Question] API - Status Codes

### ISSUE THREAD

**Issue by newacc12** [vkhorikov/CSharpFunctionalExtensions#153]
Can I somehow different between a Result.Fail<T> that failed because a validation error and another because the entity was not found?

Scenario: My API Layer calls my Application Layer to update an entity. The Application Layer does a couple of input/business validations and if those fail it returns Result.Fail<T> which the API converts to a 400 status code and returns to the client. Sometimes the Application Layer can't find the entity to be updated for whatever reason. In this case I am still returning a Result.Fail<T> but I would like to be able to return a 404 from API. It doesn't look like I can differentiate between these two Result.Fail.

**Comment by space-alien** [comment]
Instead of using a `Result` for this, I throw a custom exception (e.g. `NotFoundException`). My web API then catches this exception with a custom `ExceptionFilterAttribute`, which switches on the exception type to return the appropriate HTTP response - e.g. `404`, in this case.

For what it's worth, I take the same approach with validation errors too. In that case I throw a custom `ValidationException`.

I find this approach avoids a lot of boilerplate code (e.g. translating failure types into HTTP responses). And although some may have differing opinions on this, I like to throw an exception when I want to be sure that something that really must fail (i.e. invalid user input), definitely will fail.

**Comment by dibley1973** [comment]
@space-alien. Should exceptions not be used for "exceptional" circumstances, not validation errors which _are_ expected circumstances?

**Comment by space-alien** [comment]
@dibley1973 - Well, this is the differing opinion I mentioned. ;) I agree that validation errors are not exceptional, but depending on the application, I think the benefits can outweigh the negatives. In my application: sharing common code pathways, having a single exception filter in the web API, eliminating lots of boilerplate - which improves code readability, and improved robustness: i.e. an exception fails safe no matter how the method was called, whereas raising a custom error requires the caller to correctly handle the value that is returned.

**Comment by dibley1973** [comment]
@space-alien, fair play, I can see your reasoning. I'm just from the "don't use exceptions for logic/program flow" school, but there is no single "right" solution.

**Comment by vkhorikov** [comment]
@newacc12 someone posted a similar question here, take a look: https://github.com/vkhorikov/CqrsInPractice/issues/5

Another way to handle this (which is my preferable way) is to return `Result<Maybe<T>>`. The outer `Result` wrapper shows that the operation can fail, and the inner `Maybe` -- that a no-value is a perfectly valid result.
