### ISSUE TITLE
[usage question] Purposes of Bind and Map methods

### ISSUE THREAD

**Issue by rulrok** [vkhorikov/CSharpFunctionalExtensions#161]
Hello,

I see that `Bind` and `Map` are similar in implementation.

In both cases, if result is a failure, they just return a new failure converting the type from `T` to `K`.

While `Map` internally returns a `Result.Success` (with many overloads), in `Bind` you're supposed to pass in a function which itself uses `Result.X`.

Is one a syntactical sugar for the other? They seem equivalent.

What are your recommendations about usage of them?

**Extra question**: Where the `bind` concepts comes? I've seen this library moved from `OnSuccess` to `Tap` which for me was alien terminology so far. Is `Bind` inspired from another language/framework/programming paradigm? 

Thanks.

**Comment by vkhorikov** [comment]
I recommend this article for the difference between `Map` and `Bind`: https://fsharpforfunandprofit.com/posts/elevated-world-2/

The practical reason why `OnSuccess` was split into `Map` and `Bind` is because, without clear separation between `Func<T, K>` and `Func<T, Result<K>>`, different overloads often conflict with each.

**Comment by bopazyn** [comment]
I belive it is the same idea as `Select` and `SelectMany` for collections in c#, isn't it?

**Comment by vkhorikov** [comment]
Exactly. `Select` is a `map` in the functional programming terminology; `SelectMany` is a `bind`.

Mixing them together would introduce the same issues `OnSuccess` fell into -- to many overloads and weird compilation errors.
