### ISSUE TITLE
How to provide a Failure Result with item from list

### ISSUE THREAD

**Issue by robertlarkins** [vkhorikov/CSharpFunctionalExtensions#226]
The `Result` class is useful for indicating success an failure of an action. However, I have a situation like this that I'm trying to use `Result` with:
```c#
public SomeResultStructure AddAnimalExaminations(IEnumerable<AnimalExamination> animalExaminations)
{
    var failedAdds = new List<AnimalExamination>();

    foreach (var examination in animalExaminations)
    {
        var result = AddAnimalExamination(animalExamination);

        if (result.IsFailure)
        {
            // Add the failed item and result message
        }
    }

    Result.Success(); // No or empty result list sent back.
}

public Result AddAnimalExamination(AnimalExamination animalExamination)
{
    var existingAnimalExamination = this.animalExaminations.Find(x => x.Animal == animalExamination.Animal);

    if (!(existingAnimalExamination is null))
    {
        return Result.Failure("This animal examination already exists");
    }

    animalExamination.Add(animalExamination);

    return Result.Success();
}
```
I need to handle the failed `AnimalExamination` items from the calling class, so need to return them. Does `Result` have the capability to provide a failure case along with the item that caused the failure? If not, is this capability worth `Result` having, or is trying to use `Result` in this manner incorrect?

**Comment by robertlarkins** [comment]
I should have made it clearer. In this example those methods are in an `Examination` class which contains a list of `AnimalExamination`, so a failure occurs when trying to add an `AnimalExamination` but one already exists for that animal. In which case this double up needs to be put into an error table. So I would like to indicate in the `AddAnimalInspections` method either all animals were added successfully, or if any could not be added then return these ones to be dealt with accordingly (along with the error message).

I'm wondering whether the calling class should just call the singular add method `AddAnimalExamination` rather than the add multiple method `AddAnimalExaminations`?

**Comment by vkhorikov** [comment]
It depends on what you are going to do with the list of failed examinations. The usual approach is to use `Result<unit, YourCustomErrorType>` (`unit` -- due to there being no variations of `Result<TError>` without `TValue`). The client code can also call the singular methods one by one, it's fine too.

Also, as a side note: looks like you are passing an internal entity `AnimalExamination` to the `Examination` aggregate. It's best to let `Examination` create that internal entity by itself. Exmaple: https://github.com/vkhorikov/DddAndEFCore/blob/master/src/App/Student.cs#L36-L37 (here, `Enrollment` is analogous to `AnimalExamination`).

**Comment by robertlarkins** [comment]
Thanks, I think that functionality covers what I'm wanting. Your side note was also very useful. I'll go ahead and close this issue.
