### ISSUE TITLE
Any plans to support ValueTask<T>?

### ISSUE THREAD

**Issue by JMPSequeira** [vkhorikov/CSharpFunctionalExtensions#281]
Hey,

Just like the title says.

**Comment by vkhorikov** [comment]
Not sure about that (yet). Will need to investigate what's needed for this to happen.

**Comment by cportwood** [comment]
Simple support should be a copy of Async files with Task changed to ValueTask removing the DefaultAwait if we just wish to allow for basic support for now since ConfigureAwait does work differently in ValueTask allowing you to be returned to a different synchronization context. The user can still use configure await if needed.

I could work on that and let the community play with the branch?

**Comment by vkhorikov** [comment]
Sounds good, please feel free to submit a PR. (We can start with just a couple of extension methods, to kick off a discussion.)

**Comment by cportwood** [comment]
Will do! I will get started on that this week. It is my birthday today so I will probably get to it later this week or this weekend. I like the idea of starting with a few extension methods for discussion.  It will give the community an example to use for feedback.

**Comment by vkhorikov** [comment]
Sounds great. Happy birthday!

**Comment by hankovich** [comment]
I'm sure the issue may be closed as implemented
