### ISSUE TITLE
Does it need to put async/await inside the Tap?

### ISSUE THREAD

**Issue by kevinlo** [vkhorikov/CSharpFunctionalExtensions#304]
I have discussion with my team member how the func in the Tap should be called.   Does it need to put the async/await inside the anonymous function in the Tap or it is redundant?

```cs
return _customerRepository.GetById(id)
    .ToResult("Customer with such Id is not found: " + id)
    .Tap( async customer => await customer.Promote())
```

Most of the example I found does not need it.    Inside Tap, it will await the Task returned by the customer.Promote(), right?

**Comment by vkhorikov** [comment]
There's basically no difference. It's the same as with non-anon methods, for example:

```cs
    public static Task<Result<T>> TapIf<T>(this Task<Result<T>> resultTask, bool condition, Func<T, Task> func)
    {
        if (condition)
            return resultTask.Tap(func);
        else
            return resultTask;
    }
```

There's no need to await the task here because the task is the method doesn't need the task's result. Same with the anon function: no need to await, you can just passes that task to the caller. Not awaiting a task provide a (very) slight performance benefit.

**Comment by kevinlo** [comment]
Ok.  I just want to confirm that.  Thanks.
