### ISSUE TITLE
Serialization 

### ISSUE THREAD

**Issue by TSDilov** [vkhorikov/CSharpFunctionalExtensions#529]
While the struct is marked as serializable, consider evaluating the serialization behavior and ensuring compatibility with various serialization frameworks and scenarios.

**Comment by hankovich** [comment]
Usually you don't have to serialize `Result`s as you do not serialize `Task`s or delegates, because more like an infrastructure type, not a data type. But you can take a look at [serialization support for System.Text.Json](https://github.com/vkhorikov/CSharpFunctionalExtensions/blob/master/CSharpFunctionalExtensions/Result/Json/Serialization/JsonSerializerOptionsExtensionMethods.cs) if you need it.

Could you please explain your case in more detail? Which scenario do you have, which library/format do you use?

**Comment by TSDilov** [comment]
Thank you about the comment I think there is no more discussion needed.
