### ISSUE TITLE
Help with naming extension method that executes some function and returns Result<T> if success

### ISSUE THREAD

**Issue by rctyler** [vkhorikov/CSharpFunctionalExtensions#6]
I'm writing an extension method that operates over a collection and executes some operation. It doesn't care about the output of that function, rather it returns back the original collection if the operation succeeds, else it returns a Result.Fail (and the error msg of the action) if it fails.

So instead of doing
```
DoSomething()
  .OnSuccess(x => x.DoSomethingElse())
  .OnSuccess(x => {
    DoSomethingElse2()
    return x
  })
  .OnSuccess(x => x.DoSomethingElse3())
```

I'd do something like 
```
DoSomething()
  .OnSuccess(x => x.DoSomethingElse())
  .OnSuccess(x => x.Execute(() => DoSomethingElse2()))
  .OnSuccess(x => x.DoSomethingElse3())
```

Where `Execute` is a generic function defined as

```
public static Result<T> Execute<T>(this T collection, Func<Result> fn)
   where T : IEnumerable
{
   Result res = fn();
   return res.IsSuccess
      ? Result.Ok(collection)
      : Result.Fail<T>(res.Error);
}
```

Is `Execute` an appropriate name in this case? I only care about whether an action method succeeds or not, but I'm never returning the actual results of that function so it seems misleading...how would you name that? Since I'm using your library, I figured I could use your expertise :smile:

**Comment by vkhorikov** [comment]
Naming is hard :) I can't think of any better name than `Execute` here.

However, I would recommend another approach. As I understood, you are trying to preserve the value from the previous result while still accounting for the result of executing a subsequent function.

Try this instead:

```
DoSomething()
  .OnSuccess(x => x.DoSomethingElse())
  .OnSuccess(x => x => DoSomethingElse2().Map(() => x))
  .OnSuccess(x => x.DoSomethingElse3())
```

Here, you transform `Result` into `Result<T>` thus preserving both the returned value of the previous operation and the result of the recent one. As a small hint, if you need to do the same when `DoSomethingElse2()` returns a generic result, use anonymous types:

```
DoSomething()
  .OnSuccess(x => x.DoSomethingElse())
  .OnSuccess(x => x => DoSomethingElse2().Map(y => new { x, y }))
  .OnSuccess(x => x.DoSomethingElse3())
```

BTW, the first sample you provided (with `DoSomethingElse2(); return x;`) is only applicable if `DoSomethingElse2()` can't fail (doesn't return a `Result`), otherwise you'd swallow its result by returning `x`.

**Comment by rctyler** [comment]
Thanks! I didn't notice that `Map` function, awesome.
