### ISSUE TITLE
How to share value between successive calls in the pipeline

### ISSUE THREAD

**Issue by paulvanbladel** [vkhorikov/CSharpFunctionalExtensions#60]
I have following method:
```
public async Task<Result<MyOrderModel>> GetMyOrderByOrderId(string subject, long orderId)
        {
            long customerId = 0;

            Action<Customer> keepCustomerId = (c) => customerId = c.Id;

            return await GetCustomerBySubjectAsync(subject)
               .ToResult(ErrorMessage.CustomerNotFound)
               .OnSuccess(customer => keepCustomerId(customer))
               .OnSuccess(customer => GetOrderByIdAsync(orderId).ToResult(ErrorMessage.OrderNotFound))
               .Ensure(order => order.Customer.Id == customerId, ErrorMessage.AmbigiousPrincipalCall)
               .OnSuccess(order => _mapper.Map<MyOrderModel>(order));
        }
  public async Task<Maybe<Customer>> GetCustomerBySubjectAsync(string sub)
        {
            return await _context.Customers.Where(c => c.Sub == sub).FirstOrDefaultAsync();
        }
```
In the Ensure statement I need access to a result of GetCustomerBySubjectAsync. 
For that reason I'm storing customerId in the very first OnSuccess method.

I'm sure there is a more elegant way?
Thanks in advance.

**Comment by grishchenkoa** [comment]
@paulvanbladel I know 2 possible solution

- you can save it in local variable:
```
int random = 0;

// some pipeline
.OnSuccess(_ => random = RandomService.Get())
.OnSuccess(/* other code*/)
.OnSuccess(_ => OtherService.Handle(random))
```
not good solution -- side effects

- you can create `Tuples`, `new {}` or something other in each `OnSuccess` method call and return required value until you use it:
```
// some pipeline
.OnSuccess(_ => new { Random = RandomService.Get() } )
.OnSuccess(arg => new { arg.Random, Product = ProductService.GetAny() })
.OnSuccess(arg => {
    OtherService.Handle(arg.Random);
    return new { arg.Product }
)
.OnSuccess(arg => MailService.Notify(arg.Product))
```
better solution because without side effect and clear code

**Comment by paulvanbladel** [comment]
@grishchenkoa Many thanks. Spot on. Tuples are a great addition to the c# ecosystem.

**Comment by golavr** [comment]
@ahryshchanka second solution is cumbersome and make your code not readable
also i'm not sure if it is has no side effects
the chained OnScusses caring the value can manipulate it and cause side effects
so IMHO there is no difference in the side effects aspect
i would go with the first one since it is cleaner
