### ISSUE TITLE
Maybe<DateTime> doesn't work

### ISSUE THREAD

**Issue by paparent** [vkhorikov/CSharpFunctionalExtensions#61]
Hi!

I'm trying to have optional DateTime. But when I do `Maybe<DateTime>.None`, it uses the default value which is 0001-01-01, and when I do `.HasValue`, it's true.  

Thanks !

**Comment by vkhorikov** [comment]
@robosek is correct. `Maybe <T> where T : class` would indeed be helpful in restricting the use of `Maybe` to only reference types

**Comment by paparent** [comment]
Thanks for reply. I'm not an expert on C#, but why it should only be reference types? It doesn't make sense (or could be useful) to have `Maybe<DateTime>`, or even `Maybe<int>` ?

**Comment by paparent** [comment]
Just found an old conversation on that subject (#28). So should I use `Nullable<DateTime>` ?

**Comment by robosek** [comment]
In case of `Maybe<DateTime>` or `Maybe<int>` it doesn't really make sense because it can't be null so `HasValue` is always true. But if you really want to use structures with `Maybe` you can wrap your struct types in `Nullable<T>` as you pointed out. So for example instead of `DateTime` type you can use `DateTime?` which should work.

**Comment by paparent** [comment]
@robosek  Hmm ok. I thought the Maybe monad was to encapsulate either a value, or nothing. 

And I'm more confused with the end of the discussion of #28 with "it makes sense to remove this limitation in order to enable fluent syntax with .NET value types.".

**Comment by vkhorikov** [comment]
@paparent yeah, I've flipped from one position to the other (twice). There's no ideal decision unfortunately.  Currently, I'm in the "don't allow `Maybe` on structs" camp. `Maybe` for structs introduces conflicts with the built-in `Nullable<>` and the issue you described above. As for enabling fluent syntax, it can be done by adding extension methods on `Nullable<>` instead of `Maybe<>`.

Apology for the late reply, didn't see your reply for some reason.

**Comment by stefano77it** [comment]
@paparent this issue was resolved with Issue #67 and now `Maybe<DateTime>.None` works correctly
