### ISSUE TITLE
Maybe<int>.None.HasValue is true

### ISSUE THREAD

**Issue by FrancoisM** [vkhorikov/CSharpFunctionalExtensions#67]
While tracking a bug if found that Maybe<int>.None.HasValue was true whereas my expected behavior is that any None would have no values.

**Comment by FrancoisM** [comment]
It's because of https://github.com/vkhorikov/CSharpFunctionalExtensions/blob/744c14d8f5f983f189e6688b398f7aa27ad17714/CSharpFunctionalExtensions/Maybe.cs#L22

If it only works for T being a class then you should add where T: class

**Comment by FrancoisM** [comment]
Or better: replace with

`public bool HasValue => _value != default;`

**Comment by freakingawesome** [comment]
> Or better: replace with
> 
> `public bool HasValue => _value != default;`

Comparing against `default` would have the side-effect of making zero a `None` value, which is probably unintentional.

I have submitted a [pull request](https://github.com/vkhorikov/CSharpFunctionalExtensions/pull/68) which wraps the value inside `Maybe<T>` in a class so that `null` checks work with structs as well as classes.

**Comment by FrancoisM** [comment]
Indeed in my case 0 is a `None `value but it mind not be always the case.
I'm not sure about the wrapper.
The idea of `Maybe `is to give a type to `null`. As a `struct `cannot be `null`, then I think `Maybe `should not be used with a `struct `in the first place. My mistake. I'm more in favor of `where T: class` now that I think about it.

**Comment by freakingawesome** [comment]
I disagree that `Maybe<T>` is only about replacing `null`. It also gives you functor composability that otherwise wouldn't exist by using `.Select(...)`. Here's a contrived example:

    Maybe<string>.None.Select(_ => 42)

This would be impossible if we add the class type constraint, and currently this fails because the `None` maps to a `Maybe<int>` that has a value of zero, when logically it should map to `None`.

I updated my PR to fix these mapping issues as well.

**Comment by vkhorikov** [comment]
Published 1.11.0
